@startuml
Gender o-- Person
Person *-- Employee

class Person {
Long id
String firstName
String lastName
String middleName
Date birthDate
Gender gender
String passportNumber
}

class Employee{
Person person
Date employeeDate
Date dismissalDate
}

enum Gender {
MALE
FEMALE
}

@enduml